# Generated by Django 4.1.1 on 2024-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedln', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
    ]
