# Generated by Django 4.1.1 on 2024-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapplication', '0003_about_resume_alter_about_about_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
