# Generated by Django 4.1.1 on 2024-03-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapplication', '0005_tag_project_description_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
