# Generated by Django 4.1.1 on 2024-03-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapplication', '0006_remove_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='portfolioapplication.tag'),
        ),
    ]
